### ISSUE TITLE
GeneralizedTime should optionally accept fractional seconds

### ISSUE THREAD

**Issue by jsatchell** [XAMPPRocky/rasn#117]
According to https://obj-sys.com/asn1tutorial/node14.html, GeneralizedTime can optionally have 3 decimal places of fractional seconds. 

I had to change my generator of test data to not include the fractional part, otherwise parsing failed.

I think the format specifier needed is "%.3f". I don't think strptime has support for optional format fields - I fear this may mean trying the format alternatives in turn and accepting the first that parses successfully.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I've definitely skipped on ensuring the time types are fully accurate because there's a lot to them in the X.680 and X.690 spec, and I've mostly leaned on `chrono` to handle it for me.

> I fear this may mean trying the format alternatives in turn and accepting the first that parses successfully.

This is acceptable as an initial implementation to me. If it turns out to become a performance bottleneck, which right now I doubt because there's a lot of perf left on the floor elsewhere, because the focus has been on accuracy.

It might also be worth looking into different crates or making an issue in `chrono` as my understanding is that `GeneralizedTime` is mostly just an existing time standard.

**Comment by jsatchell** [comment]
I have made a PR - I look for decimal point or other characters, and pick most suitable parse format. Comments in code record issues to be fixed later - don't yet handle cases where seconds or minutes are omitted. Also not sure about type usage for NaiveDateTime vs DateTime<FixedOffset>

**Comment by jsatchell** [comment]
The PR resolves all this. As far as I can see, we are now fully compliant for both GeneralizedTime and UTCTime.
