### ISSUE TITLE
Implicitly tagged sequences should be constructed

### ISSUE THREAD

**Issue by mds5000** [XAMPPRocky/rasn#7]
Terrific library, and I'm trying to use it to implement a rust SNMP library.  However, I've run into an issue that I believe isn't handled correctly. I'm no expert with BER encodings, so may be mistaken.

Per X.690 (2008):
> 8.14.4 If implicit tagging was used in the definition of the type, then:
> a) the encoding shall be constructed if the base encoding is constructed, and shall be primitive otherwise;
> and
> b) the contents octets shall be the same as the contents octets of the base encoding. 

To me this would imply that if I implicitly tagged a sequence, the 'constructed' bit of the tag should be set (carried over from the base encoding). And indeed if I try this in a test case I get the following:

```rust
#[test]
    fn implicit_tagged_constructed() {
        use crate::{tag::Class, types::Implicit, AsnType, Tag};
        struct C0;
        impl AsnType for C0 {
            const TAG: Tag = Tag::new(Class::Context, 0);
        }

        let value = <Implicit<C0, _>>::new(vec![1, 2]);
        let data = &[0xA0, 6, 2, 1, 1, 2, 1, 2][..];

        assert_eq!(data, &*crate::ber::encode(&value).unwrap());
        // thread 'ber::tests::implicit_tagged_constructed' panicked at 'assertion failed: `(left == right)`
        //   left: `[160, 6, 2, 1, 1, 2, 1, 2]`,
        //. right: `[128, 6, 2, 1, 1, 2, 1, 2]`'
}
```

Happy to submit a PR if you agree this is non-conforming to the spec.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! This does indeed seem to be a bug in the library. A PR would be appreciated. If you have any questions about the codebase feel free to ask in the thread.

I'm not sure what the exact solution should be. At worse I think this might require adding a new method to encoder like `encode_implicit_prefix`, the same as there's one for `encode_explicit_prefix` that passes the type information of the wrapped type down to the BER encoder so that it can generate an initial `Identifier` and the override that with the implicit tag.

https://github.com/XAMPPRocky/rasn/blob/fae2c20677951213f490f1a9a96dea6bce6fbb46/src/enc.rs#L42

**Comment by XAMPPRocky** [comment]
Closing as this is fixed and released.
