### ISSUE TITLE
Allow using user-supplied buffer for encoding data?

### ISSUE THREAD

**Issue by repnop** [XAMPPRocky/rasn#72]
Hi, I'm working on building a SNMP client and as an optimization to prevent allocating memory on every send/receive, I want to internally store a `Vec` in my client, however there doesn't appear to be a way to provide the `Encoder` a `&mut Vec<u8>` or `&mut [u8]` to encode into, which would be really useful!

**Comment by repnop** [comment]
An alternative might be to allow passing a `Vec<u8>` into a constructor for `Encoder`, which would allow me to `core::mem::take(&mut self.my_buffer);` then swap it back after encoding -- not entirely ideal, but definitely workable and much easier to adapt `Encoder` to. If you'd be fine with this method if the above seems more difficult to support, I'd happily PR it!

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Sorry for the late reply. Overall I'm open to adding a way for to re-use the encoder buffer and would accept a PR adding this functionality. I'll only note that this won't entirely prevent allocating on every send/receive depending on the data. There are ASN.1 types that rasn always has to allocate in order to handle correctly at the layer its operating at (the main one being `SET` types). Being able to re-use the buffer would still be useful for cases where those types aren't present however.

**Comment by repnop** [comment]
Awesome! I'll see if I can find some spare time and send in a PR for that :+1:
